### ISSUE TITLE
the "example" pipeline...

### ISSUE THREAD

**Issue by rvosa** [dmlond/arangs2015#2]
...what is it?

In an ideal world we would have a couple of small ones just to show the commonalities even if you are trying to accomplish different scientific goals. Examples that I think might apply to a large number of students:
1. basic quality control: needed by everyone. Includes de-multiplexing (e.g. by adaptors/barcodes and/or by primers), trimming low quality reads, visualizing quality distributions

2a. mapping to a reference, using bwa. Requires a small reference, e.g. a chloroplast / mitochondrion / small chromosome / bacterium and a small-ish set of reads. Index the reference, map against it (paired end?), create a BAM file, visualize it.

2b. de novo assembly, using soapdenovo (?). Requires a small-ish set of reads. Optimize kmer size (kmergenie?), run the assembly, calculate statistics (N50).

2c. diversity assessment, using QIIME (?). Requires a small-ish set of reads - not too short, maybe IonTorrent or 454 (?). Cluster the reads, blast exemplars, build tree, compare samples (unifraq).

**Comment by rvosa** [comment]
Alternatively, we might consider introducing the kinds of tools you might encounter in a given pipeline, so that it might need to include:
- a couple of different scripts in different languages (python/ruby/perl) to make sure we know how to deal with their respective search paths and package managers
- some R script(s)
- some compiled binaries in C(++)
- some java program

**Comment by dmlond** [comment]
QC was a common theme in the reproducibility hackathon that NESCent ran last december, so that would probably be a good to include.  I already have a bwa alignment pipeline using the P. falciparum dataset that we used in 2014.  Since the P. falciparum reference and raw data files are in separate volumes, the bwa_aligner was created such that it can applied to any reference and raw.  So, if we want to use different genomes, that would be fine.  The main thing is that we dont want to spend too much time teaching the science and technology of the pipeline.  We really want the students to understand how to plug their own technology into a VM or Dockerized context.

As for tools, I like the idea of introducing some diversity.  I dont want to spend any time talking about how to compile C or Java.  That doesn't mean we dont include compiled C or Java.  Just that we fully automate the compilation of these with puppet or the Docker build context, and leave it to the students who are interested to find out more about how these are built.

**Comment by rvosa** [comment]
Ok, I guess we should then do some downstream analyses on BAM files, for
example to show:
- variant calling / SNP discovery
- identifying unmapped reads, maybe assemble them? detect contaminants?
- maybe something that uses annotations, e.g. extract the consensus
  sequence for a locus?

**Comment by dmlond** [comment]
Any of these sound good.  The ideal course load would be a pipeline requiring more than 2, but less than 5-6 separate analytical components.  One of the components could even be an interactive session in R, or ipython notebooks?  But, the idea is that we would compose them together using the two different reproducibility technologies.

**VM**
A single machine, whose creation and invocation is managed with vagrant, with all required software and wrapper scripts for every component.

**Docker**
Each 'component' (software + wrapper script) is built into a separate docker image.  This will demonstrate how each component can be used on its own in other situations where they are useful.

lets make a list of required software for our pipeline to put in the git repository as a README.
I think that in both cases, the data directory(ies) will be mounted to the 'machines' from the host machine.

**Comment by dmlond** [comment]
do you have any good ideas for small datasets that can be used to do your list of things?

**Comment by dmlond** [comment]
lets start collecting/documenting the software that we need.
- bwa
- samtools
  ....?

**Comment by rvosa** [comment]
I think we can close this issue. We have a simple pipeline.

**Comment by dmlond** [comment]
Yay!
